# Generated by Django 2.1.4 on 2019-01-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0003_auto_20190104_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_answer',
            field=models.TextField(default=0, max_length=150, verbose_name='ответ пользователя'),
            preserve_default=False,
        ),
    ]
