# Generated by Django 2.1.4 on 2019-01-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0004_message_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_answer',
        ),
    ]
