# Generated by Django 2.1.4 on 2019-01-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0007_auto_20190104_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.SlugField(default=2, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
