# Generated by Django 2.1.4 on 2019-01-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0008_message_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_answer',
        ),
    ]
