# Generated by Django 2.1.4 on 2019-01-06 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0010_auto_20190105_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='message',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='body.Message', verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default=2, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
