# Generated by Django 2.1.4 on 2019-01-06 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('body', '0012_auto_20190106_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='message',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
