# Generated by Django 2.1.4 on 2019-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0013_auto_20190106_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='messages', to='body.Tag'),
        ),
    ]
