# Generated by Django 2.1.4 on 2019-01-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0014_auto_20190106_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_answer',
            field=models.TextField(max_length=500, null=True, verbose_name='Ответ пользователя'),
        ),
    ]
