# Generated by Django 2.1.4 on 2019-01-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0015_message_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
