# Generated by Django 2.1.4 on 2019-01-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0017_message_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания ответа')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='end_time',
        ),
    ]
